/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiagnosticIndexRouteImport } from './routes/diagnostic.index'
import { Route as LessonNodeIdRouteImport } from './routes/lesson.$nodeId'
import { Route as DiagnosticResultsPreviewRouteImport } from './routes/diagnostic.results-preview'
import { Route as DiagnosticResultsRouteImport } from './routes/diagnostic.results'
import { Route as DiagnosticAvatarRouteImport } from './routes/diagnostic.avatar'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedDomainsRouteImport } from './routes/_authenticated/domains'
import { Route as AuthenticatedDeveloperRouteImport } from './routes/_authenticated/developer'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as DiagnosticQuestionNRouteImport } from './routes/diagnostic.question.$n'
import { Route as ApiPublicEnsureDemoUserRouteImport } from './routes/api/public/ensure-demo-user'
import { Route as AuthenticatedDailyCompleteRouteImport } from './routes/_authenticated/daily.complete'
import { Route as AuthenticatedBattleResultsRouteImport } from './routes/_authenticated/battle.results'
import { Route as AuthenticatedBattlePlayRouteImport } from './routes/_authenticated/battle.play'
import { Route as AuthenticatedBattleLeaderboardRouteImport } from './routes/_authenticated/battle.leaderboard'
import { Route as AuthenticatedBattleIntroRouteImport } from './routes/_authenticated/battle.intro'
import { Route as ApiPublicHooksGenerateDailySetsRouteImport } from './routes/api/public/hooks/generate-daily-sets'
import { Route as ApiPublicHooksGenerateBattleSetsRouteImport } from './routes/api/public/hooks/generate-battle-sets'
import { Route as AuthenticatedDailyQuestionNRouteImport } from './routes/_authenticated/daily.question.$n'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticIndexRoute = DiagnosticIndexRouteImport.update({
  id: '/diagnostic/',
  path: '/diagnostic/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonNodeIdRoute = LessonNodeIdRouteImport.update({
  id: '/lesson/$nodeId',
  path: '/lesson/$nodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticResultsPreviewRoute =
  DiagnosticResultsPreviewRouteImport.update({
    id: '/diagnostic/results-preview',
    path: '/diagnostic/results-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const DiagnosticResultsRoute = DiagnosticResultsRouteImport.update({
  id: '/diagnostic/results',
  path: '/diagnostic/results',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticAvatarRoute = DiagnosticAvatarRouteImport.update({
  id: '/diagnostic/avatar',
  path: '/diagnostic/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDomainsRoute = AuthenticatedDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeveloperRoute = AuthenticatedDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DiagnosticQuestionNRoute = DiagnosticQuestionNRouteImport.update({
  id: '/diagnostic/question/$n',
  path: '/diagnostic/question/$n',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEnsureDemoUserRoute = ApiPublicEnsureDemoUserRouteImport.update({
  id: '/api/public/ensure-demo-user',
  path: '/api/public/ensure-demo-user',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDailyCompleteRoute =
  AuthenticatedDailyCompleteRouteImport.update({
    id: '/daily/complete',
    path: '/daily/complete',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBattleResultsRoute =
  AuthenticatedBattleResultsRouteImport.update({
    id: '/battle/results',
    path: '/battle/results',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBattlePlayRoute = AuthenticatedBattlePlayRouteImport.update({
  id: '/battle/play',
  path: '/battle/play',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBattleLeaderboardRoute =
  AuthenticatedBattleLeaderboardRouteImport.update({
    id: '/battle/leaderboard',
    path: '/battle/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBattleIntroRoute =
  AuthenticatedBattleIntroRouteImport.update({
    id: '/battle/intro',
    path: '/battle/intro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksGenerateDailySetsRoute =
  ApiPublicHooksGenerateDailySetsRouteImport.update({
    id: '/api/public/hooks/generate-daily-sets',
    path: '/api/public/hooks/generate-daily-sets',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGenerateBattleSetsRoute =
  ApiPublicHooksGenerateBattleSetsRouteImport.update({
    id: '/api/public/hooks/generate-battle-sets',
    path: '/api/public/hooks/generate-battle-sets',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDailyQuestionNRoute =
  AuthenticatedDailyQuestionNRouteImport.update({
    id: '/daily/question/$n',
    path: '/daily/question/$n',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/coming-soon': typeof ComingSoonRoute
  '/dashboard': typeof DashboardRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/account': typeof AuthenticatedAccountRoute
  '/developer': typeof AuthenticatedDeveloperRoute
  '/domains': typeof AuthenticatedDomainsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/diagnostic/avatar': typeof DiagnosticAvatarRoute
  '/diagnostic/results': typeof DiagnosticResultsRoute
  '/diagnostic/results-preview': typeof DiagnosticResultsPreviewRoute
  '/lesson/$nodeId': typeof LessonNodeIdRoute
  '/diagnostic/': typeof DiagnosticIndexRoute
  '/battle/intro': typeof AuthenticatedBattleIntroRoute
  '/battle/leaderboard': typeof AuthenticatedBattleLeaderboardRoute
  '/battle/play': typeof AuthenticatedBattlePlayRoute
  '/battle/results': typeof AuthenticatedBattleResultsRoute
  '/daily/complete': typeof AuthenticatedDailyCompleteRoute
  '/api/public/ensure-demo-user': typeof ApiPublicEnsureDemoUserRoute
  '/diagnostic/question/$n': typeof DiagnosticQuestionNRoute
  '/daily/question/$n': typeof AuthenticatedDailyQuestionNRoute
  '/api/public/hooks/generate-battle-sets': typeof ApiPublicHooksGenerateBattleSetsRoute
  '/api/public/hooks/generate-daily-sets': typeof ApiPublicHooksGenerateDailySetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/coming-soon': typeof ComingSoonRoute
  '/dashboard': typeof DashboardRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/account': typeof AuthenticatedAccountRoute
  '/developer': typeof AuthenticatedDeveloperRoute
  '/domains': typeof AuthenticatedDomainsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/diagnostic/avatar': typeof DiagnosticAvatarRoute
  '/diagnostic/results': typeof DiagnosticResultsRoute
  '/diagnostic/results-preview': typeof DiagnosticResultsPreviewRoute
  '/lesson/$nodeId': typeof LessonNodeIdRoute
  '/diagnostic': typeof DiagnosticIndexRoute
  '/battle/intro': typeof AuthenticatedBattleIntroRoute
  '/battle/leaderboard': typeof AuthenticatedBattleLeaderboardRoute
  '/battle/play': typeof AuthenticatedBattlePlayRoute
  '/battle/results': typeof AuthenticatedBattleResultsRoute
  '/daily/complete': typeof AuthenticatedDailyCompleteRoute
  '/api/public/ensure-demo-user': typeof ApiPublicEnsureDemoUserRoute
  '/diagnostic/question/$n': typeof DiagnosticQuestionNRoute
  '/daily/question/$n': typeof AuthenticatedDailyQuestionNRoute
  '/api/public/hooks/generate-battle-sets': typeof ApiPublicHooksGenerateBattleSetsRoute
  '/api/public/hooks/generate-daily-sets': typeof ApiPublicHooksGenerateDailySetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/coming-soon': typeof ComingSoonRoute
  '/dashboard': typeof DashboardRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/developer': typeof AuthenticatedDeveloperRoute
  '/_authenticated/domains': typeof AuthenticatedDomainsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/diagnostic/avatar': typeof DiagnosticAvatarRoute
  '/diagnostic/results': typeof DiagnosticResultsRoute
  '/diagnostic/results-preview': typeof DiagnosticResultsPreviewRoute
  '/lesson/$nodeId': typeof LessonNodeIdRoute
  '/diagnostic/': typeof DiagnosticIndexRoute
  '/_authenticated/battle/intro': typeof AuthenticatedBattleIntroRoute
  '/_authenticated/battle/leaderboard': typeof AuthenticatedBattleLeaderboardRoute
  '/_authenticated/battle/play': typeof AuthenticatedBattlePlayRoute
  '/_authenticated/battle/results': typeof AuthenticatedBattleResultsRoute
  '/_authenticated/daily/complete': typeof AuthenticatedDailyCompleteRoute
  '/api/public/ensure-demo-user': typeof ApiPublicEnsureDemoUserRoute
  '/diagnostic/question/$n': typeof DiagnosticQuestionNRoute
  '/_authenticated/daily/question/$n': typeof AuthenticatedDailyQuestionNRoute
  '/api/public/hooks/generate-battle-sets': typeof ApiPublicHooksGenerateBattleSetsRoute
  '/api/public/hooks/generate-daily-sets': typeof ApiPublicHooksGenerateDailySetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/coming-soon'
    | '/dashboard'
    | '/plans'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/account'
    | '/developer'
    | '/domains'
    | '/home'
    | '/auth/callback'
    | '/auth/forgot'
    | '/diagnostic/avatar'
    | '/diagnostic/results'
    | '/diagnostic/results-preview'
    | '/lesson/$nodeId'
    | '/diagnostic/'
    | '/battle/intro'
    | '/battle/leaderboard'
    | '/battle/play'
    | '/battle/results'
    | '/daily/complete'
    | '/api/public/ensure-demo-user'
    | '/diagnostic/question/$n'
    | '/daily/question/$n'
    | '/api/public/hooks/generate-battle-sets'
    | '/api/public/hooks/generate-daily-sets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/coming-soon'
    | '/dashboard'
    | '/plans'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/account'
    | '/developer'
    | '/domains'
    | '/home'
    | '/auth/callback'
    | '/auth/forgot'
    | '/diagnostic/avatar'
    | '/diagnostic/results'
    | '/diagnostic/results-preview'
    | '/lesson/$nodeId'
    | '/diagnostic'
    | '/battle/intro'
    | '/battle/leaderboard'
    | '/battle/play'
    | '/battle/results'
    | '/daily/complete'
    | '/api/public/ensure-demo-user'
    | '/diagnostic/question/$n'
    | '/daily/question/$n'
    | '/api/public/hooks/generate-battle-sets'
    | '/api/public/hooks/generate-daily-sets'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/coming-soon'
    | '/dashboard'
    | '/plans'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/account'
    | '/_authenticated/developer'
    | '/_authenticated/domains'
    | '/_authenticated/home'
    | '/auth/callback'
    | '/auth/forgot'
    | '/diagnostic/avatar'
    | '/diagnostic/results'
    | '/diagnostic/results-preview'
    | '/lesson/$nodeId'
    | '/diagnostic/'
    | '/_authenticated/battle/intro'
    | '/_authenticated/battle/leaderboard'
    | '/_authenticated/battle/play'
    | '/_authenticated/battle/results'
    | '/_authenticated/daily/complete'
    | '/api/public/ensure-demo-user'
    | '/diagnostic/question/$n'
    | '/_authenticated/daily/question/$n'
    | '/api/public/hooks/generate-battle-sets'
    | '/api/public/hooks/generate-daily-sets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ComingSoonRoute: typeof ComingSoonRoute
  DashboardRoute: typeof DashboardRoute
  PlansRoute: typeof PlansRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  DiagnosticAvatarRoute: typeof DiagnosticAvatarRoute
  DiagnosticResultsRoute: typeof DiagnosticResultsRoute
  DiagnosticResultsPreviewRoute: typeof DiagnosticResultsPreviewRoute
  LessonNodeIdRoute: typeof LessonNodeIdRoute
  DiagnosticIndexRoute: typeof DiagnosticIndexRoute
  ApiPublicEnsureDemoUserRoute: typeof ApiPublicEnsureDemoUserRoute
  DiagnosticQuestionNRoute: typeof DiagnosticQuestionNRoute
  ApiPublicHooksGenerateBattleSetsRoute: typeof ApiPublicHooksGenerateBattleSetsRoute
  ApiPublicHooksGenerateDailySetsRoute: typeof ApiPublicHooksGenerateDailySetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic/': {
      id: '/diagnostic/'
      path: '/diagnostic'
      fullPath: '/diagnostic/'
      preLoaderRoute: typeof DiagnosticIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$nodeId': {
      id: '/lesson/$nodeId'
      path: '/lesson/$nodeId'
      fullPath: '/lesson/$nodeId'
      preLoaderRoute: typeof LessonNodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic/results-preview': {
      id: '/diagnostic/results-preview'
      path: '/diagnostic/results-preview'
      fullPath: '/diagnostic/results-preview'
      preLoaderRoute: typeof DiagnosticResultsPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic/results': {
      id: '/diagnostic/results'
      path: '/diagnostic/results'
      fullPath: '/diagnostic/results'
      preLoaderRoute: typeof DiagnosticResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic/avatar': {
      id: '/diagnostic/avatar'
      path: '/diagnostic/avatar'
      fullPath: '/diagnostic/avatar'
      preLoaderRoute: typeof DiagnosticAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/domains': {
      id: '/_authenticated/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof AuthenticatedDomainsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/developer': {
      id: '/_authenticated/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof AuthenticatedDeveloperRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/diagnostic/question/$n': {
      id: '/diagnostic/question/$n'
      path: '/diagnostic/question/$n'
      fullPath: '/diagnostic/question/$n'
      preLoaderRoute: typeof DiagnosticQuestionNRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ensure-demo-user': {
      id: '/api/public/ensure-demo-user'
      path: '/api/public/ensure-demo-user'
      fullPath: '/api/public/ensure-demo-user'
      preLoaderRoute: typeof ApiPublicEnsureDemoUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/daily/complete': {
      id: '/_authenticated/daily/complete'
      path: '/daily/complete'
      fullPath: '/daily/complete'
      preLoaderRoute: typeof AuthenticatedDailyCompleteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/battle/results': {
      id: '/_authenticated/battle/results'
      path: '/battle/results'
      fullPath: '/battle/results'
      preLoaderRoute: typeof AuthenticatedBattleResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/battle/play': {
      id: '/_authenticated/battle/play'
      path: '/battle/play'
      fullPath: '/battle/play'
      preLoaderRoute: typeof AuthenticatedBattlePlayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/battle/leaderboard': {
      id: '/_authenticated/battle/leaderboard'
      path: '/battle/leaderboard'
      fullPath: '/battle/leaderboard'
      preLoaderRoute: typeof AuthenticatedBattleLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/battle/intro': {
      id: '/_authenticated/battle/intro'
      path: '/battle/intro'
      fullPath: '/battle/intro'
      preLoaderRoute: typeof AuthenticatedBattleIntroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/generate-daily-sets': {
      id: '/api/public/hooks/generate-daily-sets'
      path: '/api/public/hooks/generate-daily-sets'
      fullPath: '/api/public/hooks/generate-daily-sets'
      preLoaderRoute: typeof ApiPublicHooksGenerateDailySetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-battle-sets': {
      id: '/api/public/hooks/generate-battle-sets'
      path: '/api/public/hooks/generate-battle-sets'
      fullPath: '/api/public/hooks/generate-battle-sets'
      preLoaderRoute: typeof ApiPublicHooksGenerateBattleSetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/daily/question/$n': {
      id: '/_authenticated/daily/question/$n'
      path: '/daily/question/$n'
      fullPath: '/daily/question/$n'
      preLoaderRoute: typeof AuthenticatedDailyQuestionNRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedDeveloperRoute: typeof AuthenticatedDeveloperRoute
  AuthenticatedDomainsRoute: typeof AuthenticatedDomainsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedBattleIntroRoute: typeof AuthenticatedBattleIntroRoute
  AuthenticatedBattleLeaderboardRoute: typeof AuthenticatedBattleLeaderboardRoute
  AuthenticatedBattlePlayRoute: typeof AuthenticatedBattlePlayRoute
  AuthenticatedBattleResultsRoute: typeof AuthenticatedBattleResultsRoute
  AuthenticatedDailyCompleteRoute: typeof AuthenticatedDailyCompleteRoute
  AuthenticatedDailyQuestionNRoute: typeof AuthenticatedDailyQuestionNRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedDeveloperRoute: AuthenticatedDeveloperRoute,
  AuthenticatedDomainsRoute: AuthenticatedDomainsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedBattleIntroRoute: AuthenticatedBattleIntroRoute,
  AuthenticatedBattleLeaderboardRoute: AuthenticatedBattleLeaderboardRoute,
  AuthenticatedBattlePlayRoute: AuthenticatedBattlePlayRoute,
  AuthenticatedBattleResultsRoute: AuthenticatedBattleResultsRoute,
  AuthenticatedDailyCompleteRoute: AuthenticatedDailyCompleteRoute,
  AuthenticatedDailyQuestionNRoute: AuthenticatedDailyQuestionNRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotRoute: typeof AuthForgotRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotRoute: AuthForgotRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ComingSoonRoute: ComingSoonRoute,
  DashboardRoute: DashboardRoute,
  PlansRoute: PlansRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  DiagnosticAvatarRoute: DiagnosticAvatarRoute,
  DiagnosticResultsRoute: DiagnosticResultsRoute,
  DiagnosticResultsPreviewRoute: DiagnosticResultsPreviewRoute,
  LessonNodeIdRoute: LessonNodeIdRoute,
  DiagnosticIndexRoute: DiagnosticIndexRoute,
  ApiPublicEnsureDemoUserRoute: ApiPublicEnsureDemoUserRoute,
  DiagnosticQuestionNRoute: DiagnosticQuestionNRoute,
  ApiPublicHooksGenerateBattleSetsRoute: ApiPublicHooksGenerateBattleSetsRoute,
  ApiPublicHooksGenerateDailySetsRoute: ApiPublicHooksGenerateDailySetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
