/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiagnosticIndexRouteImport } from './routes/diagnostic.index'
import { Route as LessonNodeIdRouteImport } from './routes/lesson.$nodeId'
import { Route as LearnReadingWritingRouteImport } from './routes/learn.reading-writing'
import { Route as LearnMathRouteImport } from './routes/learn.math'
import { Route as DiagnosticResultsPreviewRouteImport } from './routes/diagnostic.results-preview'
import { Route as DiagnosticResultsRouteImport } from './routes/diagnostic.results'
import { Route as DiagnosticAvatarRouteImport } from './routes/diagnostic.avatar'
import { Route as DiagnosticQuestionNRouteImport } from './routes/diagnostic.question.$n'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticIndexRoute = DiagnosticIndexRouteImport.update({
  id: '/diagnostic/',
  path: '/diagnostic/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonNodeIdRoute = LessonNodeIdRouteImport.update({
  id: '/lesson/$nodeId',
  path: '/lesson/$nodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnReadingWritingRoute = LearnReadingWritingRouteImport.update({
  id: '/learn/reading-writing',
  path: '/learn/reading-writing',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnMathRoute = LearnMathRouteImport.update({
  id: '/learn/math',
  path: '/learn/math',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticResultsPreviewRoute =
  DiagnosticResultsPreviewRouteImport.update({
    id: '/diagnostic/results-preview',
    path: '/diagnostic/results-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const DiagnosticResultsRoute = DiagnosticResultsRouteImport.update({
  id: '/diagnostic/results',
  path: '/diagnostic/results',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticAvatarRoute = DiagnosticAvatarRouteImport.update({
  id: '/diagnostic/avatar',
  path: '/diagnostic/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticQuestionNRoute = DiagnosticQuestionNRouteImport.update({
  id: '/diagnostic/question/$n',
  path: '/diagnostic/question/$n',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coming-soon': typeof ComingSoonRoute
  '/dashboard': typeof DashboardRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/diagnostic/avatar': typeof DiagnosticAvatarRoute
  '/diagnostic/results': typeof DiagnosticResultsRoute
  '/diagnostic/results-preview': typeof DiagnosticResultsPreviewRoute
  '/learn/math': typeof LearnMathRoute
  '/learn/reading-writing': typeof LearnReadingWritingRoute
  '/lesson/$nodeId': typeof LessonNodeIdRoute
  '/diagnostic/': typeof DiagnosticIndexRoute
  '/diagnostic/question/$n': typeof DiagnosticQuestionNRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coming-soon': typeof ComingSoonRoute
  '/dashboard': typeof DashboardRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/diagnostic/avatar': typeof DiagnosticAvatarRoute
  '/diagnostic/results': typeof DiagnosticResultsRoute
  '/diagnostic/results-preview': typeof DiagnosticResultsPreviewRoute
  '/learn/math': typeof LearnMathRoute
  '/learn/reading-writing': typeof LearnReadingWritingRoute
  '/lesson/$nodeId': typeof LessonNodeIdRoute
  '/diagnostic': typeof DiagnosticIndexRoute
  '/diagnostic/question/$n': typeof DiagnosticQuestionNRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coming-soon': typeof ComingSoonRoute
  '/dashboard': typeof DashboardRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/diagnostic/avatar': typeof DiagnosticAvatarRoute
  '/diagnostic/results': typeof DiagnosticResultsRoute
  '/diagnostic/results-preview': typeof DiagnosticResultsPreviewRoute
  '/learn/math': typeof LearnMathRoute
  '/learn/reading-writing': typeof LearnReadingWritingRoute
  '/lesson/$nodeId': typeof LessonNodeIdRoute
  '/diagnostic/': typeof DiagnosticIndexRoute
  '/diagnostic/question/$n': typeof DiagnosticQuestionNRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coming-soon'
    | '/dashboard'
    | '/plans'
    | '/privacy'
    | '/profile'
    | '/signup'
    | '/diagnostic/avatar'
    | '/diagnostic/results'
    | '/diagnostic/results-preview'
    | '/learn/math'
    | '/learn/reading-writing'
    | '/lesson/$nodeId'
    | '/diagnostic/'
    | '/diagnostic/question/$n'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coming-soon'
    | '/dashboard'
    | '/plans'
    | '/privacy'
    | '/profile'
    | '/signup'
    | '/diagnostic/avatar'
    | '/diagnostic/results'
    | '/diagnostic/results-preview'
    | '/learn/math'
    | '/learn/reading-writing'
    | '/lesson/$nodeId'
    | '/diagnostic'
    | '/diagnostic/question/$n'
  id:
    | '__root__'
    | '/'
    | '/coming-soon'
    | '/dashboard'
    | '/plans'
    | '/privacy'
    | '/profile'
    | '/signup'
    | '/diagnostic/avatar'
    | '/diagnostic/results'
    | '/diagnostic/results-preview'
    | '/learn/math'
    | '/learn/reading-writing'
    | '/lesson/$nodeId'
    | '/diagnostic/'
    | '/diagnostic/question/$n'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComingSoonRoute: typeof ComingSoonRoute
  DashboardRoute: typeof DashboardRoute
  PlansRoute: typeof PlansRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  DiagnosticAvatarRoute: typeof DiagnosticAvatarRoute
  DiagnosticResultsRoute: typeof DiagnosticResultsRoute
  DiagnosticResultsPreviewRoute: typeof DiagnosticResultsPreviewRoute
  LearnMathRoute: typeof LearnMathRoute
  LearnReadingWritingRoute: typeof LearnReadingWritingRoute
  LessonNodeIdRoute: typeof LessonNodeIdRoute
  DiagnosticIndexRoute: typeof DiagnosticIndexRoute
  DiagnosticQuestionNRoute: typeof DiagnosticQuestionNRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic/': {
      id: '/diagnostic/'
      path: '/diagnostic'
      fullPath: '/diagnostic/'
      preLoaderRoute: typeof DiagnosticIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$nodeId': {
      id: '/lesson/$nodeId'
      path: '/lesson/$nodeId'
      fullPath: '/lesson/$nodeId'
      preLoaderRoute: typeof LessonNodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/reading-writing': {
      id: '/learn/reading-writing'
      path: '/learn/reading-writing'
      fullPath: '/learn/reading-writing'
      preLoaderRoute: typeof LearnReadingWritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/math': {
      id: '/learn/math'
      path: '/learn/math'
      fullPath: '/learn/math'
      preLoaderRoute: typeof LearnMathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic/results-preview': {
      id: '/diagnostic/results-preview'
      path: '/diagnostic/results-preview'
      fullPath: '/diagnostic/results-preview'
      preLoaderRoute: typeof DiagnosticResultsPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic/results': {
      id: '/diagnostic/results'
      path: '/diagnostic/results'
      fullPath: '/diagnostic/results'
      preLoaderRoute: typeof DiagnosticResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic/avatar': {
      id: '/diagnostic/avatar'
      path: '/diagnostic/avatar'
      fullPath: '/diagnostic/avatar'
      preLoaderRoute: typeof DiagnosticAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic/question/$n': {
      id: '/diagnostic/question/$n'
      path: '/diagnostic/question/$n'
      fullPath: '/diagnostic/question/$n'
      preLoaderRoute: typeof DiagnosticQuestionNRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComingSoonRoute: ComingSoonRoute,
  DashboardRoute: DashboardRoute,
  PlansRoute: PlansRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  DiagnosticAvatarRoute: DiagnosticAvatarRoute,
  DiagnosticResultsRoute: DiagnosticResultsRoute,
  DiagnosticResultsPreviewRoute: DiagnosticResultsPreviewRoute,
  LearnMathRoute: LearnMathRoute,
  LearnReadingWritingRoute: LearnReadingWritingRoute,
  LessonNodeIdRoute: LessonNodeIdRoute,
  DiagnosticIndexRoute: DiagnosticIndexRoute,
  DiagnosticQuestionNRoute: DiagnosticQuestionNRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
