// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    console.warn(`[Supabase] Missing env var(s): ${missing.join(', ')}. Returning no-op client.`);
    return null as unknown as ReturnType<typeof createClient<Database>>;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// No-op stub: any property access returns a chainable function that resolves
// to `{ data: null, error: null }`. Lets the app keep running without auth.
function createNoopClient(): any {
  const handler: ProxyHandler<any> = {
    get(_t, prop) {
      if (prop === 'then') return undefined;
      if (prop === 'subscribe' || prop === 'unsubscribe') return () => ({ data: { subscription: { unsubscribe() {} } } });
      const fn: any = (..._args: any[]) => proxy;
      return new Proxy(fn, handler);
    },
  };
  const proxy: any = new Proxy(function noop() {}, {
    ...handler,
    apply: () => Promise.resolve({ data: null, error: null }),
  });
  return proxy;
}

const _noop = createNoopClient();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (_supabase === undefined) {
      try { _supabase = createSupabaseClient(); } catch { _supabase = null as any; }
    }
    if (!_supabase) return Reflect.get(_noop, prop, receiver);
    return Reflect.get(_supabase, prop, receiver);
  },
});


